package com.dawaaii.service.security.model;

public enum Permission {
    ADMIN_PORTAL_LOGIN,
    USER_MANAGEMENT,
    TRIP_MANAGEMENT,
    VEHICLE_MANAGEMENT,
    DEVICE_MANAGEMENT,
    EVENT_MANAGEMENT,
    PRODUCT_MANAGEMENT,
    ORDER_MANAGEMENT,
    MONITOR_APPS,
    CUSTOMER_SUPPORT_MANAGEMENT,
    PROMO_CODE_MANAGEMENT,
    PROMOTIONAL_MESSAGE_MANAGEMENT,
    SUBSCRIPTION_MANAGEMENT
}
